// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvv1S5oU9eZgCZr8_QMezr1d50Nnh2xEg',
    appId: '1:170368463908:web:fa615cf1a7fe96372314b1',
    messagingSenderId: '170368463908',
    projectId: 'thebuzz-804a7',
    authDomain: 'thebuzz-804a7.firebaseapp.com',
    storageBucket: 'thebuzz-804a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJqzryO6gln0o46WJB8VJ2bDWhWVZnjhY',
    appId: '1:170368463908:android:3f7c0a8476a86be12314b1',
    messagingSenderId: '170368463908',
    projectId: 'thebuzz-804a7',
    storageBucket: 'thebuzz-804a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGiQEFsYofDzQhw30HS0qi2M8UOZM_pg',
    appId: '1:170368463908:ios:bf4e79613f65fa9b2314b1',
    messagingSenderId: '170368463908',
    projectId: 'thebuzz-804a7',
    storageBucket: 'thebuzz-804a7.firebasestorage.app',
    androidClientId: '170368463908-1dnhrk0i0o2jn00nj7ls70jc8th6ne97.apps.googleusercontent.com',
    iosClientId: '170368463908-io3b1cppn2i1rppvevm890rnn5eboied.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideasApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHGiQEFsYofDzQhw30HS0qi2M8UOZM_pg',
    appId: '1:170368463908:ios:bf4e79613f65fa9b2314b1',
    messagingSenderId: '170368463908',
    projectId: 'thebuzz-804a7',
    storageBucket: 'thebuzz-804a7.firebasestorage.app',
    androidClientId: '170368463908-1dnhrk0i0o2jn00nj7ls70jc8th6ne97.apps.googleusercontent.com',
    iosClientId: '170368463908-io3b1cppn2i1rppvevm890rnn5eboied.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideasApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvv1S5oU9eZgCZr8_QMezr1d50Nnh2xEg',
    appId: '1:170368463908:web:6b45258c80f0db332314b1',
    messagingSenderId: '170368463908',
    projectId: 'thebuzz-804a7',
    authDomain: 'thebuzz-804a7.firebaseapp.com',
    storageBucket: 'thebuzz-804a7.firebasestorage.app',
  );

}